### ISSUE TITLE
Is Docker image available for 6.5.3 version?

### ISSUE THREAD

**Issue by kovurusaisachin** [pjhampton/kibana-prometheus-exporter#132]

**Comment by pjhampton** [comment]
Hey @kovurusaisachin 

Thanks for your interest in this project. There is a release for [6.5.3 here](https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.5.3). It doesn't make too much sense to build a docker image around this one kibana plugin - this is because if you're a plugin kind-of dev you probably want multiple plugins. You can see my instruction on how to build a docker image through here: https://github.com/pjhampton/kibana-prometheus-exporter#docker

Hope that helps 🤘

**Comment by kovurusaisachin** [comment]
Thanks, @pjhampton.I have kibana 6.5.3 version running on my Kubernetes cluster. If I want to use this exporter what are the feasible options that I have?

**Comment by pjhampton** [comment]
@kovurusaisachin you could use whatever you are using in your k8s cluster as a base image and install the plugin that way. This is a pretty good SO explanation.

https://stackoverflow.com/questions/46558739/how-to-install-plugin-on-github-to-kibana-running-on-container

Does that help?

**Comment by kovurusaisachin** [comment]
Thanks, @pjhampton.
