### ISSUE TITLE
create dashbords

### ISSUE THREAD

**Issue by vinayGudi** [pjhampton/kibana-prometheus-exporter#155]
sorry i am new here.. i don't know how to create dashboards with that metrics in kibana.
if it is metricbeat when can set output to es and  create visualizations from there 

when i try to install it from cmd given in readme ... it is not working  giving no such file or dir kibana-plugin
hope u got my problem :)

thanks!

**Comment by pjhampton** [comment]
Hey @vinayGudi 👋 
Welcome and no need to apologize.

This plugin is to expose [Prometheus metrics](https://prometheus.io/docs/introduction/overview/) to a pull-based Prometheus job, likely to be visualized in Grafana. I provide an example Grafana template in the [grafana/](https://github.com/pjhampton/kibana-prometheus-exporter/tree/master/grafana) directory of this repo. I've seen people use Kibana instead of Grafana for this but I haven't really looked too much into it.

It comes down to what you are monitoring. I have seen system architectures with both Promethus/Grafana running alongside ES/Kibana/Beats/etc. But something tells me you don't want a Prom/Grafana setup.

Check out this official guide from Elastic on how to get started with MetricBeat: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-installation.html
Kibana dashboards can be auto installed with the instructions here: https://www.elastic.co/guide/en/beats/metricbeat/current/load-kibana-dashboards.html

Hope that helps.

**Comment by pjhampton** [comment]
Going to close this out. Feel free to reach out again if you need any help @vinayGudi 💚
