### ISSUE TITLE
How to calculate Kinabalu heap used?

### ISSUE THREAD

**Issue by shingou0120** [pjhampton/kibana-prometheus-exporter#261]
Hi, I use this exporter to monitor my kibana.
As I read wiki page here, kibana_heap_max_in_bytes means how much the kibana can use when jvm initialized.
But I query this metric in prometheus, the graph of value is not stable(up and down)
So I am wondering where it goes wrong? Should I upgrade exporter version to 7.17.x from 7.1.0.x?
Or any other issue I should fix first?

**Comment by pjhampton** [comment]
Hey @shingou0120,

Thanks for reaching out! That is correct, there was a bug found in 7.10.1 reported in https://github.com/pjhampton/kibana-prometheus-exporter/issues/219 and fixed in https://github.com/pjhampton/kibana-prometheus-exporter/pull/221. This only applies to releases from 7.10.1 onwards, and earlier versions are still affected by this bug. 

I do recommend you upgrade **your entire Elastic stack to 7.17.X for various reasons**, including security and then install this plugin. If you need additional assistance I'm happy to help! :-)
