### ISSUE TITLE
getting issue 404 in 6.2.4 plugin in kibana (6.2.4)

### ISSUE THREAD

**Issue by ankit20000** [pjhampton/kibana-prometheus-exporter#262]
I have installed the kibana-prometheus-exporter exporter using bin/kibana-plugin install https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/6.2.4/kibana-prometheus-exporter-6.2.4.zip and installation has been successfully done but getting the 404 curl -k http://localhost:5601/_prometheus/metrics/..

**Comment by ankit20000** [comment]
i have restarted the kibana after plugin installation but same error and  below is the dameon.log after restarting the kibana



["plugin","warning"],"pid":21286,"path":"/usr/share/kibana/plugins/kibana-prometheus-exporter","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/kibana-prometheus-exporter"}
Feb 24 17:27:59 kibana[21286]: {"type":"log","@timestamp":"2022-02-24T11:57:59Z","tags":["info","optimize"],"pid":21286,"message":"Optimizing and caching bundles for stateSessionStorageRedirect, status_page, timelion and kibana. This may take a few minutes"}

**Comment by pjhampton** [comment]
Hey @ankit20000,

Bad news - I don't support plugin releases older than 7.10 (https://github.com/pjhampton/kibana-prometheus-exporter/blob/main/RELEASES.md), otherwise, I would be maintaining the likely equivalent to 100 projects. Hope you understand.

I can give you 2 recommendations though: 

  - Upgrade your Elastic stack to something more modern such as `7.17.0` or `8.0.0`, or at very least `6.8.6` I strongly suggest this due to various reasons.
  - Fork this repo, and try to fix it yourself. I can advise on this for you if you need help.

**Comment by ankit20000** [comment]
we will upgrade it but before we need to use this exporter so please help me to fix this issue . 

Please let me know if you need any logs or anyfile

**Comment by ankit20000** [comment]
I am installing it on ubuntu 18.04 amd and the version of the kibana 6.2.4

**Comment by ankit20000** [comment]
@pjhampton please provide the solution

**Comment by pjhampton** [comment]
Hey @ankit20000 

I don't support plugin releases older than 7.10 (https://github.com/pjhampton/kibana-prometheus-exporter/blob/main/RELEASES.md). As I maintain this as part of the community Prometheus and Elastic community for free, my commercial work has to come first for obvious reasons. I will hopefully get looking at this next week for you. Please be patient and consider forking the project and working on the code yourself to find the problem.
